import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      /*
       * Every source file, not merely the ones a test happened to import.
       * Reporting only what was imported flatters the number by picking its
       * own denominator: it counted 63% while leaving every component out,
       * because the UI is exercised by Playwright, which contributes nothing
       * here. Read this as "what the unit tests reach", with the e2e suite
       * covering the rest — one number cannot stand for both.
       */
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test/**',
        // Generated by the router plugin at build time.
        'src/app/routeTree.gen.ts',
        // Bootstrap and the service worker: no seam to call them through, and
        // both are covered by the suite that loads the built app.
        'src/main.tsx',
        'src/sw.ts',
        'src/vite-env.d.ts',
      ],
      reporter: ['text-summary', 'json-summary', 'html'],
    },
  },
})
