import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      /*
       * Every source file, not merely the ones a test happened to import.
       * Reporting only what was imported flatters the number by picking its
       * own denominator: it counted 63% while leaving every component out,
       * because the UI is exercised by Playwright, which contributes nothing
       * here. Read this as "what the unit tests reach", with the e2e suite
       * covering the rest — one number cannot stand for both.
       */
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test/**',
        // Generated by the router plugin at build time.
        'src/app/routeTree.gen.ts',
        // Bootstrap and the service worker: no seam to call them through, and
        // both are covered by the suite that loads the built app.
        'src/main.tsx',
        'src/sw.ts',
        'src/vite-env.d.ts',
      ],
      reporter: ['text-summary', 'json-summary', 'html'],
      /*
       * Per area, not one number for everything.
       *
       * These layers are not equally worth testing and averaging them hides
       * exactly the thing worth knowing: `domain` is pure decisions and
       * should stay near total, while `services` is mostly a wrapper around
       * connectionFor → provider → Dexie that the Playwright suite drives
       * against a real server — unit tests there would largely assert the
       * mock. A single global figure would let a drop in the first be paid
       * for by growth in the second.
       *
       * Each sits a few points under what the suite manages today: tight
       * enough to catch a real regression, loose enough that deleting a
       * well-covered file does not turn the build red on its own. Raise them
       * when the work raises the number, rather than leaving slack to grow.
       */
      thresholds: {
        // The whole tree, UI included. A floor against a collapse, no more:
        // most of what it measures is components the e2e suite covers and
        // this metric cannot see.
        statements: 52,
        branches: 45,
        functions: 40,
        lines: 52,
        'src/domain/**': { statements: 95, branches: 88, functions: 95, lines: 95 },
        'src/lib/**': { statements: 92, branches: 82, functions: 90, lines: 93 },
        'src/storage/**': { statements: 92, branches: 85, functions: 87, lines: 93 },
        'src/providers/**': { statements: 90, branches: 81, functions: 84, lines: 90 },
        'src/sync/**': { statements: 85, branches: 76, functions: 85, lines: 89 },
        'src/services/**': { statements: 92, branches: 82, functions: 90, lines: 94 },
      },
    },
  },
})
